name: Shell commands

on: [push]

jobs:
  run-shell-command: 
    runs-on: ubuntu-22.04
    steps:
      - name: echo just a string
        run: echo "sunny day, eh?"
      - name: multiline
        run: |
          node -v
          npm -v