name: Shell commands

on: [push]

jobs:
  run-shell-command: 
    runs-on: ubuntu-22.04
    steps:
      - name: echo just a string
        run: echo "sunny day, eh?"
      - name: multiline
        run: |
          node -v
          npm -v
      - name: just python commands
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-windows-commands:
    runs-on: windows-latest
    steps:
      - name: Directory PowerShell
        run: Get-Location
      - name: Directoy Bash
        run: bash
